# Generated by Django 6.0.6 on 2026-07-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
