# Generated by Django 6.0.6 on 2026-07-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='after_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='fast_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='installation_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
    ]
