# Generated by Django 6.0.6 on 2026-07-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0003_product_after_sales_product_fast_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
