# Generated by Django 6.0.6 on 2026-07-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
