# Generated by Django 6.0.6 on 2026-07-21 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tp_app', '0006_blogcategory_blogpost_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
